# GENERAL

# Window
WINDOW_WIDTH = 768
WINDOW_HEIGHT = 768
BORDER_SPACE = 2
CAPTION_STRING = 'Player One by Machinae Supremacy'

# Engine
FPS = 60

# Player
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_VELOCITY = 6
PLAYER_BULLET_VELOCITY = 16
PLAYER_BULLET_WIDTH = 8
PLAYER_BULLET_HEIGHT = 8
PLAYER_SHOOTING_PERIOD = 200

# Unused constant for a possible speed boost ability
PLAYER_SPRINT_DURATION = 2
PLAYER_SPRINT_VELOCITY = 15

# Green enemy
GREEN_ENEMY_WIDTH = 64
GREEN_ENEMY_HEIGHT = 64
GREEN_ENEMY_VELOCITY = 3
GREEN_ENEMY_SPAWN_PERIOD = 1000
